name: build

on:
  push:
    branches:
      - main

jobs:
  build_package:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      version: 16.6.1 # renovate: datasource=gitlab-releases depName=gitlab-org/gitlab-runner versioning=regex:^(?<major>\d+)(\.(?<minor>\d+))(\.(?<patch>\d+))$ extractVersion=^v(?<version>\d+\.\d+.\d+)
      latest: true
    secrets: inherit
